In [1]:
import pandas as pd
import shap
import joblib
import matplotlib.pyplot as plt

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [3]:
df = pd.read_csv("../data/predictive_maintenance.csv")

print(df.shape)

df.head()

(10000, 14)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [4]:
df = df.drop(
    ["UDI", "Product ID"],
    axis=1
)

df = pd.get_dummies(
    df,
    columns=["Type"],
    drop_first=True
)

df.columns = (
    df.columns
      .str.replace('[', '', regex=False)
      .str.replace(']', '', regex=False)
      .str.replace(' ', '_')
)

print(df.columns)

Index(['Air_temperature_K', 'Process_temperature_K', 'Rotational_speed_rpm',
       'Torque_Nm', 'Tool_wear_min', 'Machine_failure', 'TWF', 'HDF', 'PWF',
       'OSF', 'RNF', 'Type_L', 'Type_M'],
      dtype='str')

In [5]:
df["Temp_Diff"] = (
    df["Process_temperature_K"]
    - df["Air_temperature_K"]
)

df["Power"] = (
    df["Torque_Nm"]
    * df["Rotational_speed_rpm"]
)

df.head()

,Air_temperature_K,Process_temperature_K,Rotational_speed_rpm,Torque_Nm,Tool_wear_min,Machine_failure,TWF,HDF,PWF,OSF,RNF,Type_L,Type_M,Temp_Diff,Power
0,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,False,True,10.5,66382.8
1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,True,False,10.5,65190.4
2,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,True,False,10.4,74001.2
3,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,True,False,10.4,56603.5
4,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,True,False,10.5,56320.0

In [6]:
X = df.drop(
    "Machine_failure",
    axis=1
)

print(X.shape)

(10000, 14)

In [7]:
model = joblib.load(
    "../models/xgboost_model_v2.pkl"
)

print(type(model))

<class 'xgboost.sklearn.XGBClassifier'>

In [8]:
explainer = shap.TreeExplainer(model)

print("Explainer Created")

Explainer Created

In [13]:
print("X Shape:", X.shape)
print("Features:", len(X.columns))

X Shape: (10000, 14)
Features: 14

In [14]:
print(model.n_features_in_)

16

In [15]:
print("Current Features")

for col in X.columns:
    print(col)

Current Features
Air_temperature_K
Process_temperature_K
Rotational_speed_rpm
Torque_Nm
Tool_wear_min
TWF
HDF
PWF
OSF
RNF
Type_L
Type_M
Temp_Diff
Power

In [16]:
print("Expected Features")

print(model.get_booster().feature_names)

Expected Features
['Air_temperature_K', 'Process_temperature_K', 'Rotational_speed_rpm', 'Torque_Nm', 'Tool_wear_min', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF', 'Type_L', 'Type_M', 'Temp_Diff', 'Power', 'Wear_Level_Medium', 'Wear_Level_High']

In [21]:
print(X.shape)

print(model.n_features_in_)

(10000, 14)
16

In [22]:
print(len(X.columns))

14

In [24]:
print(X.shape)
print(model.n_features_in_)
print(len(X.columns))

(10000, 14)
16
14